# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_auto_20170709_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='usuario',
        ),
    ]
