# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import verify.models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_remove_identity_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=200)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to=verify.models.date_path)),
                ('clave', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
