# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_auto_20170709_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='clave',
        ),
        migrations.AddField(
            model_name='registro',
            name='faceId',
            field=models.CharField(default='sin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='username',
            field=models.CharField(default='sin', max_length=20),
            preserve_default=False,
        ),
    ]
