# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import verify.models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0006_auto_20170709_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('faceId', models.CharField(max_length=50)),
                ('sesion_file', models.FileField(upload_to=verify.models.date_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
